In [3]:
import pandas as pd

In [4]:
#reading data
df = pd.read_excel('Canada.xlsx', sheet_name='Canada by Citizenship',
skiprows=range(20), skipfooter=2)
df

,Type,Coverage,OdName,AREA,AreaName,REG,RegName,DEV,DevName,1980,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,Immigrants,Foreigners,Afghanistan,935,Asia,5501,Southern Asia,902,Developing regions,16,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
1,Immigrants,Foreigners,Albania,908,Europe,925,Southern Europe,901,Developed regions,1,...,1450,1223,856,702,560,716,561,539,620,603
2,Immigrants,Foreigners,Algeria,903,Africa,912,Northern Africa,902,Developing regions,80,...,3616,3626,4807,3623,4005,5393,4752,4325,3774,4331
3,Immigrants,Foreigners,American Samoa,909,Oceania,957,Polynesia,902,Developing regions,0,...,0,0,1,0,0,0,0,0,0,0
4,Immigrants,Foreigners,Andorra,908,Europe,925,Southern Europe,901,Developed regions,0,...,0,0,1,1,0,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Immigrants,Foreigners,Viet Nam,935,Asia,920,South-Eastern Asia,902,Developing regions,1191,...,1816,1852,3153,2574,1784,2171,1942,1723,1731,2112
191,Immigrants,Foreigners,Western Sahara,903,Africa,912,Northern Africa,902,Developing regions,0,...,0,0,1,0,0,0,0,0,0,0
192,Immigrants,Foreigners,Yemen,935,Asia,922,Western Asia,902,Developing regions,1,...,124,161,140,122,133,128,211,160,174,217
193,Immigrants,Foreigners,Zambia,903,Africa,910,Eastern Africa,902,Developing regions,11,...,56,91,77,71,64,60,102,69,46,59
194,Immigrants,Foreigners,Zimbabwe,903,Africa,910,Eastern Africa,902,Developing regions,72,...,1450,615,454,663,611,508,494,434,437,407

In [5]:
type(df)

pandas.core.frame.DataFrame

In [6]:
#data previewing
df.head()

,Type,Coverage,OdName,AREA,AreaName,REG,RegName,DEV,DevName,1980,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,Immigrants,Foreigners,Afghanistan,935,Asia,5501,Southern Asia,902,Developing regions,16,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
1,Immigrants,Foreigners,Albania,908,Europe,925,Southern Europe,901,Developed regions,1,...,1450,1223,856,702,560,716,561,539,620,603
2,Immigrants,Foreigners,Algeria,903,Africa,912,Northern Africa,902,Developing regions,80,...,3616,3626,4807,3623,4005,5393,4752,4325,3774,4331
3,Immigrants,Foreigners,American Samoa,909,Oceania,957,Polynesia,902,Developing regions,0,...,0,0,1,0,0,0,0,0,0,0
4,Immigrants,Foreigners,Andorra,908,Europe,925,Southern Europe,901,Developed regions,0,...,0,0,1,1,0,0,0,0,1,1

In [7]:
df.tail()

,Type,Coverage,OdName,AREA,AreaName,REG,RegName,DEV,DevName,1980,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
190,Immigrants,Foreigners,Viet Nam,935,Asia,920,South-Eastern Asia,902,Developing regions,1191,...,1816,1852,3153,2574,1784,2171,1942,1723,1731,2112
191,Immigrants,Foreigners,Western Sahara,903,Africa,912,Northern Africa,902,Developing regions,0,...,0,0,1,0,0,0,0,0,0,0
192,Immigrants,Foreigners,Yemen,935,Asia,922,Western Asia,902,Developing regions,1,...,124,161,140,122,133,128,211,160,174,217
193,Immigrants,Foreigners,Zambia,903,Africa,910,Eastern Africa,902,Developing regions,11,...,56,91,77,71,64,60,102,69,46,59
194,Immigrants,Foreigners,Zimbabwe,903,Africa,910,Eastern Africa,902,Developing regions,72,...,1450,615,454,663,611,508,494,434,437,407

In [8]:
df.columns.shape

(43,)

In [9]:
df.size

8385

In [10]:
df.ndim

2

In [11]:
df.dtypes

Type        object
Coverage    object
OdName      object
AREA         int64
AreaName    object
REG          int64
RegName     object
DEV          int64
DevName     object
1980         int64
1981         int64
1982         int64
1983         int64
1984         int64
1985         int64
1986         int64
1987         int64
1988         int64
1989         int64
1990         int64
1991         int64
1992         int64
1993         int64
1994         int64
1995         int64
1996         int64
1997         int64
1998         int64
1999         int64
2000         int64
2001         int64
2002         int64
2003         int64
2004         int64
2005         int64
2006         int64
2007         int64
2008         int64
2009         int64
2010         int64
2011         int64
2012         int64
2013         int64
dtype: object

In [12]:
#accessing rows and columns
#columns
df.OdName
#this will return a series

0         Afghanistan
1             Albania
2             Algeria
3      American Samoa
4             Andorra
            ...
190          Viet Nam
191    Western Sahara
192             Yemen
193            Zambia
194          Zimbabwe
Name: OdName, Length: 195, dtype: object

In [13]:
type(df.OdName)

pandas.core.series.Series

In [14]:
df[['AreaName', 'OdName', 1991, 2010, 2012]]

    AreaName          OdName  1991  2010  2012
0       Asia     Afghanistan  1378  1758  2635
1     Europe         Albania    21   561   620
2     Africa         Algeria   872  4752  3774
3    Oceania  American Samoa     0     0     0
4     Europe         Andorra     0     0     1
..       ...             ...   ...   ...   ...
190     Asia        Viet Nam  5870  1942  1731
191   Africa  Western Sahara     1     0     0
192     Asia           Yemen    18   211   174
193   Africa          Zambia    69   102    46
194   Africa        Zimbabwe    94   494   437

[195 rows x 5 columns]

In [15]:
# accessing rows
df[20:30] #cannot be used for single row

,Type,Coverage,OdName,AREA,AreaName,REG,RegName,DEV,DevName,1980,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
20,Immigrants,Foreigners,Bhutan,935,Asia,5501,Southern Asia,902,Developing regions,0,...,1,5,10,7,36,865,1464,1879,1075,487
21,Immigrants,Foreigners,Bolivia (Plurinational State of),904,Latin America and the Caribbean,931,South America,902,Developing regions,44,...,85,134,139,107,143,214,180,86,83,107
22,Immigrants,Foreigners,Bosnia and Herzegovina,908,Europe,925,Southern Europe,901,Developed regions,0,...,188,211,217,209,182,156,168,140,121,119
23,Immigrants,Foreigners,Botswana,903,Africa,913,Southern Africa,902,Developing regions,10,...,9,7,11,8,28,15,42,53,64,76
24,Immigrants,Foreigners,Brazil,904,Latin America and the Caribbean,931,South America,902,Developing regions,211,...,917,969,1181,1746,2138,2509,2598,1508,1642,1714
25,Immigrants,Foreigners,Brunei Darussalam,935,Asia,920,South-Eastern Asia,902,Developing regions,79,...,3,4,5,11,10,5,12,6,3,6
26,Immigrants,Foreigners,Bulgaria,908,Europe,923,Eastern Europe,901,Developed regions,24,...,2022,1738,1419,1172,994,784,556,365,451,512
27,Immigrants,Foreigners,Burkina Faso,903,Africa,914,Western Africa,902,Developing regions,2,...,97,91,147,136,139,162,186,144,269,322
28,Immigrants,Foreigners,Burundi,903,Africa,910,Eastern Africa,902,Developing regions,0,...,559,626,468,614,448,566,529,604,684,480
29,Immigrants,Foreigners,Cabo Verde,903,Africa,914,Western Africa,902,Developing regions,1,...,3,5,7,2,5,1,3,3,6,2

In [16]:
df.loc[10]

Type               Immigrants
Coverage           Foreigners
OdName                Austria
AREA                      908
AreaName               Europe
REG                       926
RegName        Western Europe
DEV                       901
DevName     Developed regions
1980                      234
1981                      238
1982                      201
1983                      117
1984                      127
1985                      165
1986                      196
1987                      265
1988                      198
1989                      227
1990                      158
1991                      189
1992                      131
1993                      132
1994                      133
1995                      153
1996                      191
1997                      152
1998                      190
1999                      117
2000                       97
2001                      134
2002                       87
2003                      113
2004                      118
2005                      122
2006                      102
2007                       98
2008                       91
2009                      109
2010                      124
2011                       84
2012                      102
2013                       90
Name: 10, dtype: object

In [17]:
type(df.loc)

pandas.core.indexing._LocIndexer

In [18]:
df.loc[10:20]

,Type,Coverage,OdName,AREA,AreaName,REG,RegName,DEV,DevName,1980,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
10,Immigrants,Foreigners,Austria,908,Europe,926,Western Europe,901,Developed regions,234,...,118,122,102,98,91,109,124,84,102,90
11,Immigrants,Foreigners,Azerbaijan,935,Asia,922,Western Asia,902,Developing regions,0,...,230,359,236,203,125,165,209,138,161,57
12,Immigrants,Foreigners,Bahamas,904,Latin America and the Caribbean,915,Caribbean,902,Developing regions,26,...,13,14,18,23,30,27,25,40,60,55
13,Immigrants,Foreigners,Bahrain,935,Asia,922,Western Asia,902,Developing regions,0,...,12,12,12,22,9,35,28,21,39,32
14,Immigrants,Foreigners,Bangladesh,935,Asia,5501,Southern Asia,902,Developing regions,83,...,2660,4171,4014,2897,2939,2104,4721,2694,2640,3789
15,Immigrants,Foreigners,Barbados,904,Latin America and the Caribbean,915,Caribbean,902,Developing regions,372,...,90,111,97,130,134,125,121,97,132,97
16,Immigrants,Foreigners,Belarus,908,Europe,923,Eastern Europe,901,Developed regions,0,...,543,558,439,568,524,454,438,357,277,247
17,Immigrants,Foreigners,Belgium,908,Europe,926,Western Europe,901,Developed regions,511,...,411,400,302,363,335,358,363,332,402,379
18,Immigrants,Foreigners,Belize,904,Latin America and the Caribbean,916,Central America,902,Developing regions,16,...,25,37,24,28,48,38,39,36,34,53
19,Immigrants,Foreigners,Benin,903,Africa,914,Western Africa,902,Developing regions,2,...,112,95,116,183,205,238,290,284,391,397
20,Immigrants,Foreigners,Bhutan,935,Asia,5501,Southern Asia,902,Developing regions,0,...,1,5,10,7,36,865,1464,1879,1075,487

In [19]:
df.OdName.index  #you can get series index

RangeIndex(start=0, stop=195, step=1)

In [20]:
df.OdName.values  #you can get series values

array(['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra',
       'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
       'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin',
       'Bhutan', 'Bolivia (Plurinational State of)',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi',
       'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada',
       'Central African Republic', 'Chad', 'Chile', 'China',
       'China, Hong Kong Special Administrative Region',
       'China, Macao Special Administrative Region', 'Colombia',
       'Comoros', 'Congo', 'Costa Rica', "Côte d'Ivoire", 'Croatia',
       'Cuba', 'Cyprus', 'Czech Republic',
       "Democratic People's Republic of Korea",
       'Democratic Republic of the Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon', 'Gambia',
       'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala',
       'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras',
       'Hungary', 'Iceland', 'India', 'Indonesia',
       'Iran (Islamic Republic of)', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
       'Kuwait', 'Kyrgyzstan', "Lao People's Democratic Republic",
       'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya',
       'Liechtenstein', 'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi',
       'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands',
       'Mauritania', 'Mauritius', 'Mexico', 'Monaco', 'Mongolia',
       'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia',
       'Nauru', 'Nepal', 'Netherlands', 'New Caledonia', 'New Zealand',
       'Nicaragua', 'Niger', 'Nigeria', 'Norway', 'Oman', 'Pakistan',
       'Palau', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru',
       'Philippines', 'Poland', 'Portugal', 'Qatar', 'Republic of Korea',
       'Republic of Moldova', 'Romania', 'Russian Federation', 'Rwanda',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'Samoa', 'San Marino',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Somalia', 'South Africa', 'Spain', 'Sri Lanka',
       'State of Palestine', 'Sudan', 'Suriname', 'Swaziland', 'Sweden',
       'Switzerland', 'Syrian Arab Republic', 'Tajikistan', 'Thailand',
       'The former Yugoslav Republic of Macedonia', 'Togo', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
       'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom of Great Britain and Northern Ireland',
       'United Republic of Tanzania', 'United States of America',
       'Uruguay', 'Uzbekistan', 'Vanuatu',
       'Venezuela (Bolivarian Republic of)', 'Viet Nam', 'Western Sahara',
       'Yemen', 'Zambia', 'Zimbabwe'], dtype=object)

In [21]:
#find rows from 100-135
#find immigration count for the years 2000-2010
df[100:136]

,Type,Coverage,OdName,AREA,AreaName,REG,RegName,DEV,DevName,1980,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
100,Immigrants,Foreigners,Liechtenstein,908,Europe,926,Western Europe,901,Developed regions,1,...,0,1,0,0,1,1,0,2,1,0
101,Immigrants,Foreigners,Lithuania,908,Europe,924,Northern Europe,901,Developed regions,1,...,220,167,113,108,109,63,57,52,77,145
102,Immigrants,Foreigners,Luxembourg,908,Europe,926,Western Europe,901,Developed regions,14,...,9,10,9,9,3,5,8,11,6,7
103,Immigrants,Foreigners,Madagascar,903,Africa,910,Eastern Africa,902,Developing regions,22,...,79,88,96,115,118,169,178,148,165,229
104,Immigrants,Foreigners,Malawi,903,Africa,910,Eastern Africa,902,Developing regions,5,...,17,23,15,13,5,10,28,16,9,10
105,Immigrants,Foreigners,Malaysia,935,Asia,920,South-Eastern Asia,902,Developing regions,786,...,401,593,580,600,658,640,802,409,358,204
106,Immigrants,Foreigners,Maldives,935,Asia,5501,Southern Asia,902,Developing regions,0,...,1,0,0,2,1,7,4,3,1,1
107,Immigrants,Foreigners,Mali,903,Africa,914,Western Africa,902,Developing regions,4,...,87,87,114,143,154,164,170,155,191,190
108,Immigrants,Foreigners,Malta,908,Europe,925,Southern Europe,901,Developed regions,191,...,28,28,24,7,21,18,17,8,9,4
109,Immigrants,Foreigners,Marshall Islands,909,Oceania,954,Micronesia,902,Developing regions,0,...,0,0,0,2,0,0,0,0,0,0
110,Immigrants,Foreigners,Mauritania,903,Africa,914,Western Africa,902,Developing regions,5,...,60,86,124,96,112,83,74,54,77,57
111,Immigrants,Foreigners,Mauritius,903,Africa,910,Eastern Africa,902,Developing regions,306,...,702,696,512,507,714,872,1455,1146,799,1203
112,Immigrants,Foreigners,Mexico,904,Latin America and the Caribbean,916,Central America,902,Developing regions,409,...,2259,2837,2844,3239,2856,3092,3865,3947,4227,3996
113,Immigrants,Foreigners,Monaco,908,Europe,926,Western Europe,901,Developed regions,0,...,1,1,1,1,0,0,4,1,3,1
114,Immigrants,Foreigners,Mongolia,935,Asia,906,Eastern Asia,902,Developing regions,0,...,34,59,64,82,59,118,169,103,68,99
115,Immigrants,Foreigners,Montenegro,908,Europe,925,Southern Europe,901,Developed regions,0,...,0,0,0,7,19,10,14,19,26,9
116,Immigrants,Foreigners,Morocco,903,Africa,912,Northern Africa,902,Developing regions,325,...,3686,2939,3322,4021,4226,5532,6242,4399,3878,3261
117,Immigrants,Foreigners,Mozambique,903,Africa,910,Eastern Africa,902,Developing regions,0,...,8,5,9,5,5,12,7,3,4,12
118,Immigrants,Foreigners,Myanmar,935,Asia,920,South-Eastern Asia,902,Developing regions,80,...,191,210,953,1887,975,1153,556,368,193,262
119,Immigrants,Foreigners,Namibia,903,Africa,913,Southern Africa,902,Developing regions,0,...,9,6,19,13,26,14,16,23,24,83
120,Immigrants,Foreigners,Nauru,909,Oceania,954,Micronesia,902,Developing regions,1,...,1,1,1,0,0,1,0,0,0,1
121,Immigrants,Foreigners,Nepal,935,Asia,5501,Southern Asia,902,Developing regions,1,...,404,607,540,511,581,561,1392,1129,1185,1308
122,Immigrants,Foreigners,Netherlands,908,Europe,926,Western Europe,901,Developed regions,1889,...,749,813,837,615,818,786,759,586,504,395
123,Immigrants,Foreigners,New Caledonia,909,Oceania,928,Melanesia,902,Developing regions,0,...,0,0,0,0,1,0,0,0,0,2
124,Immigrants,Foreigners,New Zealand,909,Oceania,927,Australia and New Zealand,901,Developed regions,602,...,350,370,318,350,480,520,490,375,417,415
125,Immigrants,Foreigners,Nicaragua,904,Latin America and the Caribbean,916,Central America,902,Developing regions,18,...,67,79,96,76,124,116,94,123,106,96
126,Immigrants,Foreigners,Niger,903,Africa,914,Western Africa,902,Developing regions,0,...,38,59,57,75,75,82,80,90,95,105
127,Immigrants,Foreigners,Nigeria,903,Africa,914,Western Africa,902,Developing regions,81,...,1518,2236,2594,2375,2109,3156,3906,3103,3443,4172
128,Immigrants,Foreigners,Norway,908,Europe,924,Northern Europe,901,Developed regions,116,...,73,57,53,73,66,75,46,49,53,59
129,Immigrants,Foreigners,Oman,935,Asia,922,Western Asia,902,Developing regions,0,...,12,14,18,16,10,7,14,10,13,11
130,Immigrants,Foreigners,Pakistan,935,Asia,5501,Southern Asia,902,Developing regions,978,...,13399,14314,13127,10124,8994,7217,6811,7468,11227,12603
131,Immigrants,Foreigners,Palau,909,Oceania,954,Micronesia,902,Developing regions,0,...,0,0,0,1,0,0,0,0,0,0
132,Immigrants,Foreigners,Panama,904,Latin America and the Caribbean,916,Central America,902,Developing regions,13,...,38,57,73,63,52,73,65,49,34,43
133,Immigrants,Foreigners,Papua New Guinea,909,Oceania,928,Melanesia,902,Developing regions,0,...,1,1,0,0,9,1,3,0,3,3
134,Immigrants,Foreigners,Paraguay,904,Latin America and the Caribbean,931,South America,902,Developing regions,45,...,74,75,88,98,95,88,89,83,55,66
135,Immigrants,Foreigners,Peru,904,Latin America and the Caribbean,931,South America,902,Developing regions,317,...,1460,1653,1473,1490,1094,1884,1283,886,787,682

In [22]:
df[df['OdName']=='India']

,Type,Coverage,OdName,AREA,AreaName,REG,RegName,DEV,DevName,1980,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
79,Immigrants,Foreigners,India,935,Asia,5501,Southern Asia,902,Developing regions,8880,...,28235,36210,33848,28742,28261,29456,34235,27509,30933,33087

In [23]:
df[range(2000, 2011)]

     2000  2001  2002  2003  2004  2005  2006  2007  2008  2009  2010
0    3326  4067  3697  3479  2978  3436  3009  2652  2111  1746  1758
1    1816  1602  1021   853  1450  1223   856   702   560   716   561
2    2867  3418  3406  3072  3616  3626  4807  3623  4005  5393  4752
3       0     0     0     0     0     0     1     0     0     0     0
4       0     1     0     2     0     0     1     1     0     0     0
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
190  1803  2117  2291  1713  1816  1852  3153  2574  1784  2171  1942
191     0     0     0     0     0     0     1     0     0     0     0
192   122   181   171   113   124   161   140   122   133   128   211
193    39    78    50    46    56    91    77    71    64    60   102
194    98   110   191   669  1450   615   454   663   611   508   494

[195 rows x 11 columns]

In [24]:
china_df = df[df['OdName']=='China']
china_df[[1995,2010]]

     1995   2010
36  14398  30391

In [28]:
df[df['AreaName']=='Asia'].shape

(49, 43)

In [27]:
df[df['AreaName']=='Europe'].shape

(43, 43)

##Manipulating data

In [43]:
#Renaming columns
df.rename(columns={'OdName' : 'Country', 'AreaName': 'Continent', 'DevName': 'DevStatus'}, inplace=True)

In [31]:
df.Type.unique()

array(['Immigrants'], dtype=object)

In [36]:
df.drop(columns = ['Type', 'REG', 'DEV'])

,Coverage,OdName,AREA,AreaName,RegName,DevName,1980,1981,1982,1983,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,Foreigners,Afghanistan,935,Asia,Southern Asia,Developing regions,16,39,39,47,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
1,Foreigners,Albania,908,Europe,Southern Europe,Developed regions,1,0,0,0,...,1450,1223,856,702,560,716,561,539,620,603
2,Foreigners,Algeria,903,Africa,Northern Africa,Developing regions,80,67,71,69,...,3616,3626,4807,3623,4005,5393,4752,4325,3774,4331
3,Foreigners,American Samoa,909,Oceania,Polynesia,Developing regions,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
4,Foreigners,Andorra,908,Europe,Southern Europe,Developed regions,0,0,0,0,...,0,0,1,1,0,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Foreigners,Viet Nam,935,Asia,South-Eastern Asia,Developing regions,1191,1829,2162,3404,...,1816,1852,3153,2574,1784,2171,1942,1723,1731,2112
191,Foreigners,Western Sahara,903,Africa,Northern Africa,Developing regions,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
192,Foreigners,Yemen,935,Asia,Western Asia,Developing regions,1,2,1,6,...,124,161,140,122,133,128,211,160,174,217
193,Foreigners,Zambia,903,Africa,Eastern Africa,Developing regions,11,17,11,7,...,56,91,77,71,64,60,102,69,46,59
194,Foreigners,Zimbabwe,903,Africa,Eastern Africa,Developing regions,72,114,102,44,...,1450,615,454,663,611,508,494,434,437,407

In [44]:
#find the immigrants from India and China and Afganistan in year 1990 - 2005
df.loc[(df['Continent']== 'Asia') & (df['DevStatus']== 'Developing regions')]

,Type,Coverage,Country,AREA,Continent,REG,RegName,DEV,DevStatus,1980,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,Immigrants,Foreigners,Afghanistan,935,Asia,5501,Southern Asia,902,Developing regions,16,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
8,Immigrants,Foreigners,Armenia,935,Asia,922,Western Asia,902,Developing regions,0,...,147,224,218,198,205,267,252,236,258,207
11,Immigrants,Foreigners,Azerbaijan,935,Asia,922,Western Asia,902,Developing regions,0,...,230,359,236,203,125,165,209,138,161,57
13,Immigrants,Foreigners,Bahrain,935,Asia,922,Western Asia,902,Developing regions,0,...,12,12,12,22,9,35,28,21,39,32
14,Immigrants,Foreigners,Bangladesh,935,Asia,5501,Southern Asia,902,Developing regions,83,...,2660,4171,4014,2897,2939,2104,4721,2694,2640,3789
20,Immigrants,Foreigners,Bhutan,935,Asia,5501,Southern Asia,902,Developing regions,0,...,1,5,10,7,36,865,1464,1879,1075,487
25,Immigrants,Foreigners,Brunei Darussalam,935,Asia,920,South-Eastern Asia,902,Developing regions,79,...,3,4,5,11,10,5,12,6,3,6
30,Immigrants,Foreigners,Cambodia,935,Asia,920,South-Eastern Asia,902,Developing regions,12,...,348,370,529,460,354,203,200,196,233,288
36,Immigrants,Foreigners,China,935,Asia,906,Eastern Asia,902,Developing regions,5123,...,36619,42584,33518,27642,30037,29622,30391,28502,33024,34129
37,Immigrants,Foreigners,"China, Hong Kong Special Administrative Region",935,Asia,906,Eastern Asia,902,Developing regions,0,...,536,729,712,674,897,657,623,591,728,774
38,Immigrants,Foreigners,"China, Macao Special Administrative Region",935,Asia,906,Eastern Asia,902,Developing regions,0,...,21,21,32,16,12,21,21,13,33,29
46,Immigrants,Foreigners,Cyprus,935,Asia,922,Western Asia,902,Developing regions,132,...,11,7,9,4,7,6,18,6,12,16
48,Immigrants,Foreigners,Democratic People's Republic of Korea,935,Asia,906,Eastern Asia,902,Developing regions,1,...,15,14,10,7,19,11,45,97,66,17
66,Immigrants,Foreigners,Georgia,935,Asia,922,Western Asia,902,Developing regions,0,...,106,114,125,132,112,128,126,139,147,125
79,Immigrants,Foreigners,India,935,Asia,5501,Southern Asia,902,Developing regions,8880,...,28235,36210,33848,28742,28261,29456,34235,27509,30933,33087
80,Immigrants,Foreigners,Indonesia,935,Asia,920,South-Eastern Asia,902,Developing regions,186,...,552,632,613,657,661,504,712,390,395,387
81,Immigrants,Foreigners,Iran (Islamic Republic of),935,Asia,5501,Southern Asia,902,Developing regions,1172,...,6348,5837,7480,6974,6475,6580,7477,7479,7534,11291
82,Immigrants,Foreigners,Iraq,935,Asia,922,Western Asia,902,Developing regions,262,...,1796,2226,1788,2406,3543,5450,5941,6196,4041,4918
84,Immigrants,Foreigners,Israel,935,Asia,922,Western Asia,902,Developing regions,1403,...,2788,2446,2625,2401,2562,2316,2755,1970,2134,1945
88,Immigrants,Foreigners,Jordan,935,Asia,922,Western Asia,902,Developing regions,177,...,1733,1940,1827,1421,1581,1235,1831,1635,1206,1255
89,Immigrants,Foreigners,Kazakhstan,935,Asia,5500,Central Asia,902,Developing regions,0,...,545,506,408,436,394,431,377,381,462,348
92,Immigrants,Foreigners,Kuwait,935,Asia,922,Western Asia,902,Developing regions,1,...,74,66,35,62,53,68,67,58,73,48
93,Immigrants,Foreigners,Kyrgyzstan,935,Asia,5500,Central Asia,902,Developing regions,0,...,245,173,161,135,168,173,157,159,278,123
94,Immigrants,Foreigners,Lao People's Democratic Republic,935,Asia,920,South-Eastern Asia,902,Developing regions,11,...,38,42,74,53,32,39,54,22,25,15
96,Immigrants,Foreigners,Lebanon,935,Asia,922,Western Asia,902,Developing regions,1409,...,3293,3709,3802,3467,3566,3077,3432,3072,1614,2172
105,Immigrants,Foreigners,Malaysia,935,Asia,920,South-Eastern Asia,902,Developing regions,786,...,401,593,580,600,658,640,802,409,358,204
106,Immigrants,Foreigners,Maldives,935,Asia,5501,Southern Asia,902,Developing regions,0,...,1,0,0,2,1,7,4,3,1,1
114,Immigrants,Foreigners,Mongolia,935,Asia,906,Eastern Asia,902,Developing regions,0,...,34,59,64,82,59,118,169,103,68,99
118,Immigrants,Foreigners,Myanmar,935,Asia,920,South-Eastern Asia,902,Developing regions,80,...,191,210,953,1887,975,1153,556,368,193,262
121,Immigrants,Foreigners,Nepal,935,Asia,5501,Southern Asia,902,Developing regions,1,...,404,607,540,511,581,561,1392,1129,1185,1308
129,Immigrants,Foreigners,Oman,935,Asia,922,Western Asia,902,Developing regions,0,...,12,14,18,16,10,7,14,10,13,11
130,Immigrants,Foreigners,Pakistan,935,Asia,5501,Southern Asia,902,Developing regions,978,...,13399,14314,13127,10124,8994,7217,6811,7468,11227,12603
136,Immigrants,Foreigners,Philippines,935,Asia,920,South-Eastern Asia,902,Developing regions,6051,...,14004,18139,18400,19837,24887,28573,38617,36765,34315,29544
139,Immigrants,Foreigners,Qatar,935,Asia,922,Western Asia,902,Developing regions,0,...,5,11,2,5,9,6,18,3,14,6
140,Immigrants,Foreigners,Republic of Korea,935,Asia,906,Eastern Asia,902,Developing regions,1011,...,5352,5832,6215,5920,7294,5874,5537,4588,5316,4509
151,Immigrants,Foreigners,Saudi Arabia,935,Asia,922,Western Asia,902,Developing regions,0,...,128,198,252,188,249,246,330,278,286,267
156,Immigrants,Foreigners,Singapore,935,Asia,920,South-Eastern Asia,902,Developing regions,241,...,311,392,298,690,734,366,805,219,146,141
162,Immigrants,Foreigners,Sri Lanka,935,Asia,5501,Southern Asia,902,Developing regions,185,...,4495,4930,4714,4123,4756,4547,4422,3309,3338,2394
163,Immigrants,Foreigners,State of Palestine,935,Asia,922,Western Asia,902,Developing regions,0,...,376,453,627,441,481,400,654,555,533,462
169,Immigrants,Foreigners,Syrian Arab Republic,935,Asia,922,Western Asia,902,Developing regions,315,...,1116,1458,1145,1056,919,917,1039,1005,650,1009
170,Immigrants,Foreigners,Tajikistan,935,Asia,5500,Central Asia,902,Developing regions,0,...,14,85,46,44,15,50,52,47,34,39
171,Immigrants,Foreigners,Thailand,935,Asia,920,South-Eastern Asia,902,Developing regions,56,...,392,575,500,487,519,512,499,396,296,400
177,Immigrants,Foreigners,Turkey,935,Asia,922,Western Asia,902,Developing regions,481,...,1736,2065,1638,1463,1122,1238,1492,1257,1068,729
178,Immigrants,Foreigners,Turkmenistan,935,Asia,5500,Central Asia,902,Developing regions,0,...,16,40,26,37,13,20,30,20,20,14
182,Immigrants,Foreigners,United Arab Emirates,935,Asia,922,Western Asia,902,Developing regions,0,...,41,31,42,37,33,37,86,60,54,46
187,Immigrants,Foreigners,Uzbekistan,935,Asia,5500,Central Asia,902,Developing regions,0,...,175,330,262,284,215,288,289,162,235,167
190,Immigrants,Foreigners,Viet Nam,935,Asia,920,South-Eastern Asia,902,Developing regions,1191,...,1816,1852,3153,2574,1784,2171,1942,1723,1731,2112
192,Immigrants,Foreigners,Yemen,935,Asia,922,Western Asia,902,Developing regions,1,...,124,161,140,122,133,128,211,160,174,217

In [46]:
#sorting dataframe
#df.sort_values(2004)  #ascending order
df.sort_values(2004, ascending=False)  # descending order

,Type,Coverage,Country,AREA,Continent,REG,RegName,DEV,DevStatus,1980,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
36,Immigrants,Foreigners,China,935,Asia,906,Eastern Asia,902,Developing regions,5123,...,36619,42584,33518,27642,30037,29622,30391,28502,33024,34129
79,Immigrants,Foreigners,India,935,Asia,5501,Southern Asia,902,Developing regions,8880,...,28235,36210,33848,28742,28261,29456,34235,27509,30933,33087
136,Immigrants,Foreigners,Philippines,935,Asia,920,South-Eastern Asia,902,Developing regions,6051,...,14004,18139,18400,19837,24887,28573,38617,36765,34315,29544
130,Immigrants,Foreigners,Pakistan,935,Asia,5501,Southern Asia,902,Developing regions,978,...,13399,14314,13127,10124,8994,7217,6811,7468,11227,12603
183,Immigrants,Foreigners,United Kingdom of Great Britain and Northern I...,908,Europe,924,Northern Europe,901,Developed regions,22045,...,7533,7258,7140,8216,8979,8876,8724,6204,6195,5827
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3,Immigrants,Foreigners,American Samoa,909,Oceania,957,Polynesia,902,Developing regions,0,...,0,0,1,0,0,0,0,0,0,0
191,Immigrants,Foreigners,Western Sahara,903,Africa,912,Northern Africa,902,Developing regions,0,...,0,0,1,0,0,0,0,0,0,0
32,Immigrants,Citizens,Canada,905,Northern America,905,Northern America,901,Developed regions,0,...,0,0,0,0,0,0,0,1,1,2
149,Immigrants,Foreigners,San Marino,908,Europe,925,Southern Europe,901,Developed regions,1,...,0,0,0,0,0,0,1,0,0,0
153,Immigrants,Foreigners,Serbia,908,Europe,925,Southern Europe,901,Developed regions,0,...,0,0,3,50,259,365,271,299,395,297

In [52]:
#find the top 10 countries in 2013.
df.sort_values(2013, ascending=False).head(10)[['Country', 2013]]

                                               Country   2013
36                                               China  34129
79                                               India  33087
136                                        Philippines  29544
130                                           Pakistan  12603
81                          Iran (Islamic Republic of)  11291
185                           United States of America   8501
183  United Kingdom of Great Britain and Northern I...   5827
63                                              France   5623
82                                                Iraq   4918
140                                  Republic of Korea   4509